import { SourceMetadata } from '../types';
import { buildYouTubeTimestampUrl, isYouTubeUrl } from './youtube';

export const downloadTranscript = (
  source: SourceMetadata,
  format: 'txt' | 'txt-timestamps' | 'json' | 'ipad-html',
) => {
  let content = '';
  let mimeType = 'text/plain';
  let extension = 'txt';

  switch (format) {
    case 'json':
      content = JSON.stringify(source, null, 2);
      mimeType = 'application/json';
      extension = 'json';
      break;
    case 'txt-timestamps':
      content = source.segments
        .map(s => `[${formatTime(s.start)}] ${s.text}`)
        .join('\n');
      break;
    case 'ipad-html':
      content = buildIpadHtml(source);
      mimeType = 'text/html;charset=utf-8';
      extension = 'html';
      break;
    case 'txt':
    default:
      content = source.segments
        .map(s => s.text)
        .join('\n');
      break;
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${source.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.${extension}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const buildIpadHtml = (source: SourceMetadata): string => {
  const youtubeEnabled = source.sourceType === 'youtube' && isYouTubeUrl(source.url);
  const segmentsHtml = source.segments
    .map((segment) => {
      const ts = formatTime(segment.start);
      const deepLink = youtubeEnabled
        ? buildYouTubeTimestampUrl(source.url, segment.start)
        : null;
      const tsHtml = deepLink
        ? `<a href="${escapeHtml(deepLink)}" target="_blank" rel="noopener noreferrer">${ts}</a>`
        : ts;
      return `
        <article class="segment">
          <div class="timestamp">${tsHtml}</div>
          <p>${escapeHtml(segment.text)}</p>
        </article>
      `;
    })
    .join('\n');

  const sourceLine = source.url ? `<p class="meta">Source: ${escapeHtml(source.url)}</p>` : '';
  const clickHelp = youtubeEnabled
    ? '<p class="meta">Tip: tap a timestamp to open YouTube at that exact moment.</p>'
    : '';

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(source.title)} - Capyap iPad Export</title>
    <style>
      :root {
        color-scheme: light dark;
      }
      body {
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        line-height: 1.6;
        background: #f8fafc;
        color: #0f172a;
      }
      main {
        max-width: 920px;
        margin: 0 auto;
        padding: 24px 20px 40px;
      }
      h1 {
        margin: 0 0 8px;
        font-size: 28px;
      }
      .meta {
        margin: 0 0 6px;
        color: #475569;
        font-size: 14px;
      }
      .section {
        margin-top: 22px;
      }
      .segment {
        border: 1px solid #e2e8f0;
        background: #ffffff;
        border-radius: 10px;
        padding: 12px 14px;
        margin-bottom: 10px;
      }
      .segment .timestamp {
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
        font-size: 13px;
        margin-bottom: 6px;
      }
      .segment .timestamp a {
        text-decoration: none;
        color: #1d4ed8;
      }
      .segment p {
        margin: 0;
        font-size: 17px;
      }
      @media (prefers-color-scheme: dark) {
        body {
          background: #020617;
          color: #e2e8f0;
        }
        .meta {
          color: #94a3b8;
        }
        .segment {
          border-color: #1e293b;
          background: #0f172a;
        }
        .segment .timestamp a {
          color: #93c5fd;
        }
      }
    </style>
  </head>
  <body>
    <main>
      <h1>${escapeHtml(source.title)}</h1>
      <p class="meta">Generated by Capyap</p>
      <p class="meta">Words: ${source.wordCount.toLocaleString()} | Segments: ${source.segments.length}</p>
      ${sourceLine}
      ${clickHelp}
      <section class="section">
        ${segmentsHtml}
      </section>
    </main>
  </body>
</html>`;
};

const escapeHtml = (value: string): string => {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
};

const formatTime = (seconds: number) => {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};
